export const images = {
  logo: {
    src: "/images/logo.webp",
    alt: "Brad's Lawn Services logo",
    w: 600,
    h: 181,
  },
  logoSm: {
    src: "/images/logo-sm.webp",
    alt: "Brad's Lawn Services logo",
    w: 200,
    h: 60,
  },
  logoPng: {
    src: "/images/logo-512.png",
    alt: "Brad's Lawn Services logo",
    w: 512,
    h: 512,
  },

  heroLawn: {
    src: "/images/hero-lawn.webp",
    alt: "Freshly mowed residential lawn with clean stripes in Battle Creek, MI",
    w: 1440,
    h: 598,
  },
  heroSnow: {
    src: "/images/hero-snow.webp",
    alt: "Snow plow clearing a commercial parking lot in Battle Creek, MI",
    w: 1440,
    h: 598,
  },
  equipmentLineup: {
    src: "/images/equipment-lineup.webp",
    alt: "Brad's Lawn Services professional equipment lineup",
    w: 800,
    h: 450,
  },
  leafTruck: {
    src: "/images/leaf-truck.webp",
    alt: "Truck loaded with leaves during fall cleanup service",
    w: 1440,
    h: 598,
  },
  aerationTines: {
    src: "/images/aeration-tines.webp",
    alt: "Close-up of core aeration tines pulling soil plugs from a lawn",
    w: 1440,
    h: 598,
  },
  brushTractor: {
    src: "/images/brush-tractor.webp",
    alt: "Tractor performing brush hogging on an overgrown field",
    w: 1000,
    h: 562,
  },

  brushHogging1: {
    src: "/images/brush-hogging-1.webp",
    alt: "Field before and during brush hogging service",
    w: 1200,
    h: 900,
  },
  brushHogging2: {
    src: "/images/brush-hogging-2.webp",
    alt: "Overgrown lot being cleared by brush hog attachment",
    w: 1184,
    h: 888,
  },
  stumpGrinder: {
    src: "/images/stump-grinder.webp",
    alt: "Stump grinding equipment removing a tree stump",
    w: 1184,
    h: 888,
  },

  aerationPlugs: {
    src: "/images/aeration-plugs.webp",
    alt: "Soil plugs on a lawn after core aeration treatment",
    w: 1200,
    h: 675,
  },
  aeratorMachine: {
    src: "/images/aerator-machine.webp",
    alt: "Walk-behind core aerator machine on a residential lawn",
    w: 644,
    h: 858,
  },
  aeratorDetail: {
    src: "/images/aerator-detail.webp",
    alt: "Detail view of core aeration equipment tines",
    w: 585,
    h: 780,
  },

  leafPickupTruck: {
    src: "/images/leaf-pickup-truck.webp",
    alt: "Pickup truck bed filled with collected leaves",
    w: 800,
    h: 450,
  },
  leafVacuumTrailer: {
    src: "/images/leaf-vacuum-trailer.webp",
    alt: "Leaf vacuum and trailer setup for fall cleanup",
    w: 1200,
    h: 900,
  },
  yardAfterCleanup: {
    src: "/images/yard-after-cleanup.webp",
    alt: "Clean yard after professional leaf removal service",
    w: 800,
    h: 600,
  },

  snowPlowBlade: {
    src: "/images/snow-plow-blade.webp",
    alt: "Snow plow blade mounted on a truck for winter service",
    w: 525,
    h: 700,
  },
  commercialSnowClearing: {
    src: "/images/commercial-snow-clearing.webp",
    alt: "Commercial parking lot after professional snow plowing",
    w: 525,
    h: 700,
  },

  badgeHaScreened: {
    src: "/images/badge-ha-screened.webp",
    alt: "HomeAdvisor Screened and Approved badge",
    w: 160,
    h: 146,
  },
  badgeHaToprated: {
    src: "/images/badge-ha-toprated.webp",
    alt: "HomeAdvisor Top Rated badge",
    w: 142,
    h: 160,
  },
  badgeHaElite: {
    src: "/images/badge-ha-elite.webp",
    alt: "HomeAdvisor Elite Service badge",
    w: 162,
    h: 155,
  },
  badgeHa3year: {
    src: "/images/badge-ha-3year.webp",
    alt: "HomeAdvisor 3 Years Screened and Approved badge",
    w: 142,
    h: 159,
  },
  badgeHa20reviews: {
    src: "/images/badge-ha-20reviews.webp",
    alt: "HomeAdvisor 20 Reviews badge",
    w: 141,
    h: 161,
  },
  badgeTtPro: {
    src: "/images/badge-tt-pro.webp",
    alt: "Thumbtack Pro 2016 badge",
    w: 200,
    h: 200,
  },
  badgeTtToppro: {
    src: "/images/badge-tt-toppro.webp",
    alt: "Thumbtack Top Pro 2018 badge",
    w: 200,
    h: 200,
  },
  badgeGoogleReview: {
    src: "/images/badge-google-review.webp",
    alt: "Google Reviews badge",
    w: 359,
    h: 104,
  },
/* ===== BEGIN 2026 PHOTOS (generated) ===== */
  /*
   * 2026 photo drop — 91 files, every one visually inspected before its
   * alt text was written. Slots carry intrinsic w/h so the masonry gallery
   * renders each photo at its true aspect ratio with zero layout shift.
   */
  snowPlowDriveway: {
    src: "/images/snow-plow-driveway.webp",
    alt: "Red snow plow blade mounted on a truck beside a cleared driveway after a Battle Creek snowfall",
    w: 1050,
    h: 1400,
  },
  snowPlowBranded: {
    src: "/images/snow-plow-branded.webp",
    alt: "Close-up of a red Western plow blade lettered Brad's Lawn Services 269-589-9458",
    w: 1400,
    h: 1050,
  },
  snowPlowRoadPov: {
    src: "/images/snow-plow-road-pov.webp",
    alt: "View over a raised plow blade while clearing a snow-covered road",
    w: 1050,
    h: 1400,
  },
  snowLotClearedCars: {
    src: "/images/snow-lot-cleared-cars.webp",
    alt: "Commercial parking lot plowed clear to the pavement with customer cars parked",
    w: 1050,
    h: 1400,
  },
  snowLotDusk: {
    src: "/images/snow-lot-dusk.webp",
    alt: "Commercial building with its parking lot cleared of snow at dusk",
    w: 1050,
    h: 1400,
  },
  snowSidewalkEdge: {
    src: "/images/snow-sidewalk-edge.webp",
    alt: "Sidewalk and curb line cleared down to bare concrete alongside a plowed lot",
    w: 1050,
    h: 1400,
  },
  snowPlowSidewalk: {
    src: "/images/snow-plow-sidewalk.webp",
    alt: "White plow blade parked beside a freshly cleared commercial sidewalk",
    w: 1050,
    h: 1400,
  },
  snowPlowTrucks: {
    src: "/images/snow-plow-trucks.webp",
    alt: "Two plow trucks with blades raised, staged in a snow-covered commercial lot",
    w: 1400,
    h: 1050,
  },
  snowLotEvening: {
    src: "/images/snow-lot-evening.webp",
    alt: "Plowed commercial lot with snow banked along the edges in the evening",
    w: 1050,
    h: 1400,
  },
  snowPlowSunrise: {
    src: "/images/snow-plow-sunrise.webp",
    alt: "Sunrise over a snow-covered lot seen across the top of a plow blade",
    w: 1050,
    h: 1400,
  },
  snowLotSunny: {
    src: "/images/snow-lot-sunny.webp",
    alt: "Single-story commercial building with its lot and drive plowed on a clear winter day",
    w: 1050,
    h: 1400,
  },
  snowEntranceCleared: {
    src: "/images/snow-entrance-cleared.webp",
    alt: "Commercial entrance and walkway cleared of snow right up to the door",
    w: 1050,
    h: 1400,
  },
  snowPlowStaged: {
    src: "/images/snow-plow-staged.webp",
    alt: "Plow truck parked beside banked snow after clearing a commercial lot",
    w: 1050,
    h: 1400,
  },
  snowDriveCommercial: {
    src: "/images/snow-drive-commercial.webp",
    alt: "Cleared commercial drive running alongside a brick building after plowing",
    w: 1050,
    h: 1400,
  },
  snowPlowTruckLot: {
    src: "/images/snow-plow-truck-lot.webp",
    alt: "Plow truck with its blade down working across a snow-covered lot",
    w: 1050,
    h: 1400,
  },
  leafCrewBlowerStreet: {
    src: "/images/leaf-crew-blower-street.webp",
    alt: "Crew running a walk-behind blower to windrow leaves toward the street for pickup",
    w: 1050,
    h: 1400,
  },
  leafTruckVacWorking: {
    src: "/images/leaf-truck-vac-working.webp",
    alt: "Brad's leaf pick-up truck and vacuum working a curbside leaf row",
    w: 1050,
    h: 1400,
  },
  leafCrewHivisTruck: {
    src: "/images/leaf-crew-hivis-truck.webp",
    alt: "Crew member in high-visibility gear feeding leaves into the vacuum truck",
    w: 1050,
    h: 1400,
  },
  leafTruckBlowerLawn: {
    src: "/images/leaf-truck-blower-lawn.webp",
    alt: "Branded leaf pick-up truck and walk-behind blower clearing a residential lawn",
    w: 1050,
    h: 1400,
  },
  leafVacBigPile: {
    src: "/images/leaf-vac-big-pile.webp",
    alt: "Crew member vacuuming a large leaf pile from a front lawn",
    w: 1050,
    h: 1400,
  },
  leafVacIntoTruck: {
    src: "/images/leaf-vac-into-truck.webp",
    alt: "Leaves being vacuumed from a curbside pile straight into the collection truck",
    w: 1050,
    h: 1400,
  },
  leafTruckStreet: {
    src: "/images/leaf-truck-street.webp",
    alt: "Brad's leaf pick-up truck working along a residential street lined with leaves",
    w: 1050,
    h: 1400,
  },
  leafBeforeBrickHouse: {
    src: "/images/leaf-before-brick-house.webp",
    alt: "Front lawn of a brick house buried under fallen leaves before cleanup",
    w: 1050,
    h: 1400,
  },
  leafAfterBrickHouse: {
    src: "/images/leaf-after-brick-house.webp",
    alt: "The same brick house with its lawn cleared of leaves after cleanup",
    w: 1050,
    h: 1400,
  },
  leafColonialRows: {
    src: "/images/leaf-colonial-rows.webp",
    alt: "Leaves blown into rows across the lawn of a colonial house ready for collection",
    w: 1400,
    h: 1050,
  },
  leafRowsSlope: {
    src: "/images/leaf-rows-slope.webp",
    alt: "Windrowed leaves running across a sloped lawn during fall cleanup",
    w: 1050,
    h: 1400,
  },
  leafYardSignCleared: {
    src: "/images/leaf-yard-sign-cleared.webp",
    alt: "Brad's leaf pick-up yard sign on a cleared colonial lawn after cleanup",
    w: 1400,
    h: 1050,
  },
  leafBeforeRanch: {
    src: "/images/leaf-before-ranch.webp",
    alt: "Ranch house front yard covered in heavy leaf fall before cleanup",
    w: 1050,
    h: 1400,
  },
  leafAfterRanch: {
    src: "/images/leaf-after-ranch.webp",
    alt: "The same ranch house with its yard cleared of leaves after cleanup",
    w: 1400,
    h: 1050,
  },
  leafBlowerBackyard: {
    src: "/images/leaf-blower-backyard.webp",
    alt: "Walk-behind blower clearing leaves from a fenced back lawn",
    w: 1050,
    h: 1400,
  },
  leafCrewDriveway: {
    src: "/images/leaf-crew-driveway.webp",
    alt: "Crew clearing leaves along a driveway with a blower and collection truck",
    w: 1050,
    h: 1400,
  },
  leafTwoCrewVac: {
    src: "/images/leaf-two-crew-vac.webp",
    alt: "Two crew members working a leaf vacuum hose across a residential lawn",
    w: 1050,
    h: 1400,
  },
  leafTruckBrandedCrew: {
    src: "/images/leaf-truck-branded-crew.webp",
    alt: "Brad's branded leaf pick-up truck with crew vacuuming leaves behind it",
    w: 1050,
    h: 1400,
  },
  leafTruckBrandedVac: {
    src: "/images/leaf-truck-branded-vac.webp",
    alt: "Crew feeding the vacuum hose beside the branded leaf pick-up truck",
    w: 1050,
    h: 1400,
  },
  leafCurbBefore: {
    src: "/images/leaf-curb-before.webp",
    alt: "Deep leaf row banked along a residential curb waiting for pickup",
    w: 1050,
    h: 1400,
  },
  leafTruckVacCurb: {
    src: "/images/leaf-truck-vac-curb.webp",
    alt: "Branded leaf pick-up truck vacuuming a curbside leaf row clean",
    w: 1050,
    h: 1400,
  },
  leafTrailerCurb: {
    src: "/images/leaf-trailer-curb.webp",
    alt: "Leaf collection trailer and truck working a leaf-lined residential street",
    w: 1400,
    h: 1050,
  },
  leafVacHoseCurb: {
    src: "/images/leaf-vac-hose-curb.webp",
    alt: "Vacuum hose drawing leaves out of a heavy curbside pile",
    w: 1050,
    h: 1400,
  },
  leafCurbAfter: {
    src: "/images/leaf-curb-after.webp",
    alt: "Curb strip cleared back to bare grass after leaf pickup",
    w: 1050,
    h: 1400,
  },
  leafBeforeStoneDrive: {
    src: "/images/leaf-before-stone-drive.webp",
    alt: "Leaf pile heaped on a driveway beside a stone retaining wall before removal",
    w: 1050,
    h: 1400,
  },
  leafAfterStoneDrive: {
    src: "/images/leaf-after-stone-drive.webp",
    alt: "The same driveway swept clean beside the stone wall after removal",
    w: 1050,
    h: 1400,
  },
  springBeforeCurb: {
    src: "/images/spring-before-curb.webp",
    alt: "Winter leaf litter banked along a curb strip before spring cleanup",
    w: 1050,
    h: 1400,
  },
  springAfterCurb: {
    src: "/images/spring-after-curb.webp",
    alt: "The same curb strip cleared to green grass after spring cleanup",
    w: 1050,
    h: 1400,
  },
  leafTractorPile: {
    src: "/images/leaf-tractor-pile.webp",
    alt: "Tractor working a long leaf pile heaped along a curb strip",
    w: 1050,
    h: 1400,
  },
  leafPileTrailer: {
    src: "/images/leaf-pile-trailer.webp",
    alt: "Large leaf pile alongside the dump trailer it is being loaded into",
    w: 1050,
    h: 1400,
  },
  leafVacTrailerSign: {
    src: "/images/leaf-vac-trailer-sign.webp",
    alt: "Leaf vacuum trailer and Brad's yard sign set up on a fall cleanup job",
    w: 1400,
    h: 1400,
  },
  leafTrailerAutumn: {
    src: "/images/leaf-trailer-autumn.webp",
    alt: "Leaf vacuum trailer and truck parked on an autumn residential street",
    w: 1050,
    h: 1400,
  },
  leafHugePile: {
    src: "/images/leaf-huge-pile.webp",
    alt: "Very large leaf pile stacked beside the vacuum trailer on a front lawn",
    w: 1054,
    h: 1400,
  },
  leafPileHouse: {
    src: "/images/leaf-pile-house.webp",
    alt: "Leaf pile and vacuum trailer in front of a two-story house during fall cleanup",
    w: 1400,
    h: 1054,
  },
  leafTrailerHose: {
    src: "/images/leaf-trailer-hose.webp",
    alt: "Vacuum trailer with its hose laid out across a residential driveway",
    w: 1400,
    h: 1054,
  },
  leafTruckMailbox: {
    src: "/images/leaf-truck-mailbox.webp",
    alt: "Branded leaf pick-up truck and crew clearing leaves beside a mailbox",
    w: 1400,
    h: 1054,
  },
  leafCrewWalkingHose: {
    src: "/images/leaf-crew-walking-hose.webp",
    alt: "Crew member carrying the vacuum hose up a driveway during fall cleanup",
    w: 1054,
    h: 1400,
  },
  leafTruckDumping: {
    src: "/images/leaf-truck-dumping.webp",
    alt: "Brad's leaf pick-up truck tipping a load of collected leaves",
    w: 1054,
    h: 1400,
  },
  lawnSpringSidewalk: {
    src: "/images/lawn-spring-sidewalk.webp",
    alt: "Green spring lawn edged cleanly along a residential sidewalk",
    w: 1050,
    h: 1400,
  },
  lawnTudorSpring: {
    src: "/images/lawn-tudor-spring.webp",
    alt: "Tudor-style house with a freshly cut spring lawn",
    w: 1400,
    h: 1050,
  },
  lawnTreeSpring: {
    src: "/images/lawn-tree-spring.webp",
    alt: "Trimmed spring lawn around a mature shade tree in front of a house",
    w: 1400,
    h: 1050,
  },
  lawnWalkClean: {
    src: "/images/lawn-walk-clean.webp",
    alt: "Clean-edged walkway running between two sections of cut lawn",
    w: 1050,
    h: 1400,
  },
  lawnWalkEdged: {
    src: "/images/lawn-walk-edged.webp",
    alt: "Sharp edging along a concrete walk with the lawn cut on both sides",
    w: 1050,
    h: 1400,
  },
  lawnSummerShrubs: {
    src: "/images/lawn-summer-shrubs.webp",
    alt: "Manicured summer lawn with rounded shrubs in front of a ranch home",
    w: 1050,
    h: 1400,
  },
  lawnSummerSlope: {
    src: "/images/lawn-summer-slope.webp",
    alt: "Trimmed shrubs and a healthy green lawn on a sloped back yard",
    w: 1050,
    h: 1400,
  },
  lawnSummerLush: {
    src: "/images/lawn-summer-lush.webp",
    alt: "Lush green summer lawn running up to a house with shaped shrubs",
    w: 1400,
    h: 1050,
  },
  lawnWideManicured: {
    src: "/images/lawn-wide-manicured.webp",
    alt: "Wide manicured lawn with a row of shaped shrubs under a clear blue sky",
    w: 1050,
    h: 1400,
  },
  lawnWideSummer: {
    src: "/images/lawn-wide-summer.webp",
    alt: "Broad summer lawn cut clean across an open residential property",
    w: 1050,
    h: 1400,
  },
  hedgeBeforeWalk: {
    src: "/images/hedge-before-walk.webp",
    alt: "Overgrown hedges crowding in over a front walkway before trimming",
    w: 1050,
    h: 1400,
  },
  hedgeAfterWalk: {
    src: "/images/hedge-after-walk.webp",
    alt: "The same walkway opened up after the hedges were cut back",
    w: 1050,
    h: 1400,
  },
  hedgeBeforeGate: {
    src: "/images/hedge-before-gate.webp",
    alt: "Overgrown shrubs swallowing a gate and path before trimming",
    w: 1050,
    h: 1400,
  },
  hedgeAfterGate: {
    src: "/images/hedge-after-gate.webp",
    alt: "The same gate and path clear after the shrubs were trimmed back",
    w: 1050,
    h: 1400,
  },
  hedgeBeforeRow: {
    src: "/images/hedge-before-row.webp",
    alt: "Long shrub row grown wild and out of shape before trimming",
    w: 1400,
    h: 1050,
  },
  hedgeAfterRow: {
    src: "/images/hedge-after-row.webp",
    alt: "The same shrub row cut back to a clean flat line",
    w: 1050,
    h: 1400,
  },
  hedgeBeforeHouse: {
    src: "/images/hedge-before-house.webp",
    alt: "Overgrown shrubs blocking the front of a house before trimming",
    w: 1050,
    h: 1400,
  },
  hedgeAfterHouse: {
    src: "/images/hedge-after-house.webp",
    alt: "The same house front opened up after the overgrown shrubs were cut back",
    w: 1050,
    h: 1400,
  },
  hedgeAfterHouse2: {
    src: "/images/hedge-after-house-2.webp",
    alt: "Trimmed shrubs and a clear walkway at the front of the house after the work",
    w: 1050,
    h: 1400,
  },
  brushBeforeTree: {
    src: "/images/brush-before-tree.webp",
    alt: "Heavy brush grown up around the base of a mature tree before clearing",
    w: 1050,
    h: 1400,
  },
  brushAfterTree: {
    src: "/images/brush-after-tree.webp",
    alt: "The same ground cleared out around the tree after brush removal",
    w: 1050,
    h: 1400,
  },
  brushBeforeMass: {
    src: "/images/brush-before-mass.webp",
    alt: "Dense overgrown shrub mass taking over a side yard before clearing",
    w: 1400,
    h: 1050,
  },
  brushAfterMass: {
    src: "/images/brush-after-mass.webp",
    alt: "The same side yard with the shrubs cut back and shaped",
    w: 1050,
    h: 1400,
  },
  hedgePorchTrimmed: {
    src: "/images/hedge-porch-trimmed.webp",
    alt: "Freshly trimmed hedge running along a screened porch with the trimmer set down",
    w: 1050,
    h: 1400,
  },
  hedgePorchClean: {
    src: "/images/hedge-porch-clean.webp",
    alt: "Neatly squared hedge line along a screened porch after trimming",
    w: 1050,
    h: 1400,
  },
  stormLogLawn: {
    src: "/images/storm-log-lawn.webp",
    alt: "Large fallen tree trunk down across a lawn with a chainsaw ready beside it",
    w: 1050,
    h: 1400,
  },
  stormChainsawCut: {
    src: "/images/storm-chainsaw-cut.webp",
    alt: "Crew member cutting a fallen trunk into sections with a chainsaw",
    w: 1050,
    h: 1400,
  },
  stormChainsawWork: {
    src: "/images/storm-chainsaw-work.webp",
    alt: "Chainsaw work sectioning a downed tree on a residential lawn",
    w: 1050,
    h: 1400,
  },
  stormCrewHelmet: {
    src: "/images/storm-crew-helmet.webp",
    alt: "Crew member in helmet and high-visibility gear cutting up a fallen tree",
    w: 1050,
    h: 1400,
  },
  stormCutClose: {
    src: "/images/storm-cut-close.webp",
    alt: "Close work cutting a large log into movable rounds",
    w: 1050,
    h: 1400,
  },
  stormCutTrunk: {
    src: "/images/storm-cut-trunk.webp",
    alt: "Sectioning the length of a fallen trunk with a chainsaw",
    w: 1050,
    h: 1400,
  },
  stormTractorSplitter: {
    src: "/images/storm-tractor-splitter.webp",
    alt: "Tractor and log splitter set up alongside the truck during storm cleanup",
    w: 1050,
    h: 1400,
  },
  stormLawnCleared: {
    src: "/images/storm-lawn-cleared.webp",
    alt: "Lawn cleared and raked flat after the fallen tree was removed",
    w: 1050,
    h: 1400,
  },
  stormChipsLawn: {
    src: "/images/storm-chips-lawn.webp",
    alt: "Wood chips left across the lawn where the tree work was carried out",
    w: 1050,
    h: 1400,
  },
  stormChipsSpread: {
    src: "/images/storm-chips-spread.webp",
    alt: "Chips and debris spread over the grass before the final cleanup pass",
    w: 1050,
    h: 1400,
  },
  equipTractorLeaves: {
    src: "/images/equip-tractor-leaves.webp",
    alt: "Compact tractor carrying a loader bucket heaped with leaves to the dump truck",
    w: 1050,
    h: 1400,
  },
  equipTractorLoading: {
    src: "/images/equip-tractor-loading.webp",
    alt: "Tractor loading collected leaves into the dump truck on a residential street",
    w: 1050,
    h: 1400,
  },
  equipLeafVacTrailer: {
    src: "/images/equip-leaf-vac-trailer.webp",
    alt: "Brad's leaf vacuum trailer parked and ready for a fall cleanup route",
    w: 1400,
    h: 1054,
  },
  /* ===== END 2026 PHOTOS (generated) ===== */
} as const;

/** Uniform shape for every slot above — all carry intrinsic dimensions. */
export type ImageSlot = { src: string; alt: string; w: number; h: number };

/**
 * Look a slot up by string key. The gallery and before/after data reference
 * slots by name, so this keeps those files free of import gymnastics while
 * still returning a single concrete type rather than a 119-member union.
 */
export function getImage(slot: string): ImageSlot | undefined {
  return (images as Record<string, ImageSlot>)[slot];
}
